# Generated by Django 4.2.13 on 2024-07-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contac",
        ),
    ]
