# Generated by Django 4.2.13 on 2024-07-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_rename_contacts_contac"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contac",
            new_name="Contact",
        ),
    ]
