# Generated by Django 4.2.13 on 2024-07-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamModel",
            new_name="Team",
        ),
    ]
