# Generated by Django 4.2.13 on 2024-07-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carsmodel",
            name="doors",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="carsmodel",
            name="fuel_type",
            field=models.CharField(max_length=50),
        ),
    ]
